[project]
name="elypsoengine"
version="0-0-1"
kmake="project.kmake"

[references]
dir_kw="../../kalawindow/build/1-7-0"
dir_kg="../../kalagraphics/build/0-0-1"
dir_kp="../../kalaphysics/build/0-0-1"
dir_ks="../../kalaserver/build/0-0-1"
dir_kl="../../kalalua/build/1-1-0"
dir_ka="../../kalaaudio/build/1-2-0"
dir_kh="../../kalaheaders"
dir_cg="../../../_forks/cgltf/_build/build/1-15-0"
dir_hb="../../../_forks/harfbuzz/_build/build/14-5-0"
dir_lo="../../../_forks/lodepng/_build/build/1-0-0"
dir_lua="../../../_forks/lua/_build/build/5-5-1"
dir_ma="../../../_forks/miniaudio/_build/build/0-11-25"
dir_vk_spv="../../../_forks/spirv-reflect/_build/build/1-4-363"
dir_vk_win="../../../_forks/spirv-reflect/_vk"
ext_kw="../external/kalawindow"
ext_kg="../external/kalagraphics"
ext_kp="../external/kalaphysics"
ext_ks="../external/kalaserver"
ext_kl="../external/kalalua"
ext_ka="../external/kalaaudio"
ext_kh="../external/kalaheaders"
ext_cg="../external/cgltf"
ext_hb="../external/harfbuzz"
ext_lo="../external/lodepng"
ext_lua="../external/lua"
ext_ma="../external/miniaudio"
ext_vk="../external/vulkan"
ext_spv="../external/spirv-reflect"
kg_files="../../kalagraphics/files"

[windows-sync]
kw_stuff=[ "${dir_kw}", "${ext_kw}", "copy" ]
kg_stuff=[ "${dir_kg}", "${ext_kg}", "copy" ]
kg_files=[ "${kg_files}", "${ext_kg}/files", "copy" ]
kp_stuff=[ "${dir_kp}", "${ext_kp}", "copy" ]
ks_stuff=[ "${dir_ks}", "${ext_ks}", "copy" ]
kl_stuff=[ "${dir_kl}", "${ext_kl}", "copy" ]
ka_stuff=[ "${dir_ka}", "${ext_ka}", "copy" ]
kh_license=[ "${dir_kh}/LICENSE.md", "${ext_kh}/LICENSE.md", "copy" ]
kh_readme=[ "${dir_kh}/README.md", "${ext_kh}/README.md", "copy" ]
kh_include=[ "${dir_kh}/include", "${ext_kh}/include", "copy" ]
cg_stuff=[ "${dir_cg}", "${ext_cg}", "copy" ]
hb_stuff=[ "${dir_hb}", "${ext_hb}", "copy" ]
lo_stuff=[ "${dir_lo}", "${ext_lo}", "copy" ]
lua_stuff=[ "${dir_lua}", "${ext_lua}", "copy" ]
ma_stuff=[ "${dir_ma}", "${ext_ma}", "copy" ]
vk_win_stuff=[ "${dir_vk_win}", "${ext_vk}", "copy" ]
vk_spv_stuff=[ "${dir_vk_spv}", "${ext_spv}", "copy" ]
kw_junk_kh=[ "${ext_kw}/kalaheaders", "", "delete" ]
kw_junk_vk_win=[ "${ext_kw}/vulkan", "", "delete" ]
kw_junk_vk_spv=[ "${ext_kw}/spirv-reflect", "", "delete" ]
kg_junk_kh=[ "${ext_kg}/kalaheaders", "", "delete" ]
kg_junk_cg=[ "${ext_kg}/cgltf", "", "delete" ]
kg_junk_hb=[ "${ext_kg}/harfbuzz", "", "delete" ]
kg_junk_lo=[ "${ext_kg}/lodepng", "", "delete" ]
kg_junk_vk_win=[ "${ext_kg}/vulkan", "", "delete" ]
kg_junk_vk_spv=[ "${ext_kg}/spirv-reflect", "", "delete" ]
kp_junk_kh=[ "${ext_kp}/kalaheaders", "", "delete" ]
ks_junk_kh=[ "${ext_ks}/kalaheaders", "", "delete" ]
kl_junk_kh=[ "${ext_kl}/kalaheaders", "", "delete" ]
kl_junk_lua=[ "${ext_kl}/lua", "", "delete" ]
ka_junk_kh=[ "${ext_ka}/kalaheaders", "", "delete" ]
ka_junk_ma=[ "${ext_ka}/miniaudio", "", "delete" ]

[windows-post-build-sync]
ee_bin_rel=[ "build/temp/release-windows/elypsoengine.lib", "build/${version}/elypsoengine.lib", "copy" ]
ee_bin_deb=[ "build/temp/debug-windows/elypsoengined.lib", "build/${version}/elypsoengined.lib", "copy" ]
ee_include=[ "include", "build/${version}/include", "copy" ]
ee_license=[ "../LICENSE.md", "build/${version}/LICENSE.md", "copy" ]
ee_readme=[ "../README.md", "build/${version}/README.md", "copy" ]
ee_changes=[ "CHANGES.md", "build/${version}/CHANGES.md", "copy" ]
kw_stuff=[ "${ext_kw}", "build/${version}/kalawindow", "copy" ]
kg_stuff=[ "${ext_kg}", "build/${version}/kalagraphics", "copy" ]
kp_stuff=[ "${ext_kp}", "build/${version}/kalaphysics", "copy" ]
ks_stuff=[ "${ext_ks}", "build/${version}/kalaserver", "copy" ]
kl_stuff=[ "${ext_kl}", "build/${version}/kalalua", "copy" ]
ka_stuff=[ "${ext_ka}", "build/${version}/kalaaudio", "copy" ]
kh_stuff=[ "${ext_kh}", "build/${version}/kalaheaders", "copy" ]
cg_stuff=[ "${ext_cg}", "build/${version}/cgltf", "copy" ]
hb_stuff=[ "${ext_hb}", "build/${version}/harfbuzz", "copy" ]
lo_stuff=[ "${ext_lo}", "build/${version}/lodepng", "copy" ]
lua_stuff=[ "${ext_lua}", "build/${version}/lua", "copy" ]
ma_stuff=[ "${ext_lua}", "build/${version}/miniaudio", "copy" ]
vk_spv_stuff=[ "${ext_spv}", "build/${version}/spirv-reflect", "copy" ]

[windows-gnu-sync]
kw_stuff=[ "${dir_kw}", "${ext_kw}", "copy" ]
kg_stuff=[ "${dir_kg}", "${ext_kg}", "copy" ]
kg_files=[ "${kg_files}", "${ext_kg}/files", "copy" ]
kp_stuff=[ "${dir_kp}", "${ext_kp}", "copy" ]
ks_stuff=[ "${dir_ks}", "${ext_ks}", "copy" ]
kl_stuff=[ "${dir_kl}", "${ext_kl}", "copy" ]
ka_stuff=[ "${dir_ka}", "${ext_ka}", "copy" ]
kh_license=[ "${dir_kh}/LICENSE.md", "${ext_kh}/LICENSE.md", "copy" ]
kh_readme=[ "${dir_kh}/README.md", "${ext_kh}/README.md", "copy" ]
kh_include=[ "${dir_kh}/include", "${ext_kh}/include", "copy" ]
cg_stuff=[ "${dir_cg}", "${ext_cg}", "copy" ]
hb_stuff=[ "${dir_hb}", "${ext_hb}", "copy" ]
lo_stuff=[ "${dir_lo}", "${ext_lo}", "copy" ]
lua_stuff=[ "${dir_lua}", "${ext_lua}", "copy" ]
ma_stuff=[ "${dir_ma}", "${ext_ma}", "copy" ]
vk_win_stuff=[ "${dir_vk_win}", "${ext_vk}", "copy" ]
vk_spv_stuff=[ "${dir_vk_spv}", "${ext_spv}", "copy" ]
kw_junk_kh=[ "${ext_kw}/kalaheaders", "", "delete" ]
kw_junk_vk_win=[ "${ext_kw}/vulkan", "", "delete" ]
kw_junk_vk_spv=[ "${ext_kw}/spirv-reflect", "", "delete" ]
kg_junk_kh=[ "${ext_kg}/kalaheaders", "", "delete" ]
kg_junk_cg=[ "${ext_kg}/cgltf", "", "delete" ]
kg_junk_hb=[ "${ext_kg}/harfbuzz", "", "delete" ]
kg_junk_lo=[ "${ext_kg}/lodepng", "", "delete" ]
kg_junk_vk_win=[ "${ext_kg}/vulkan", "", "delete" ]
kg_junk_vk_spv=[ "${ext_kg}/spirv-reflect", "", "delete" ]
kp_junk_kh=[ "${ext_kp}/kalaheaders", "", "delete" ]
ks_junk_kh=[ "${ext_ks}/kalaheaders", "", "delete" ]
kl_junk_kh=[ "${ext_kl}/kalaheaders", "", "delete" ]
kl_junk_lua=[ "${ext_kl}/lua", "", "delete" ]
ka_junk_kh=[ "${ext_ka}/kalaheaders", "", "delete" ]
ka_junk_ma=[ "${ext_ka}/miniaudio", "", "delete" ]

[windows-gnu-post-build-sync]
ee_bin_rel=[ "build/temp/release-windows-gnu/elypsoengine-gnu.lib", "build/${version}/elypsoengine-gnu.lib", "copy" ]
ee_bin_deb=[ "build/temp/debug-windows-gnu/elypsoengine-gnud.lib", "build/${version}/elypsoengine-gnud.lib", "copy" ]
ee_include=[ "include", "build/${version}/include", "copy" ]
ee_license=[ "../LICENSE.md", "build/${version}/LICENSE.md", "copy" ]
ee_readme=[ "../README.md", "build/${version}/README.md", "copy" ]
ee_changes=[ "CHANGES.md", "build/${version}/CHANGES.md", "copy" ]
kw_stuff=[ "${ext_kw}", "build/${version}/kalawindow", "copy" ]
kg_stuff=[ "${ext_kg}", "build/${version}/kalagraphics", "copy" ]
kp_stuff=[ "${ext_kp}", "build/${version}/kalaphysics", "copy" ]
ks_stuff=[ "${ext_ks}", "build/${version}/kalaserver", "copy" ]
kl_stuff=[ "${ext_kl}", "build/${version}/kalalua", "copy" ]
ka_stuff=[ "${ext_ka}", "build/${version}/kalaaudio", "copy" ]
kh_stuff=[ "${ext_kh}", "build/${version}/kalaheaders", "copy" ]
cg_stuff=[ "${ext_cg}", "build/${version}/cgltf", "copy" ]
hb_stuff=[ "${ext_hb}", "build/${version}/harfbuzz", "copy" ]
lo_stuff=[ "${ext_lo}", "build/${version}/lodepng", "copy" ]
lua_stuff=[ "${ext_lua}", "build/${version}/lua", "copy" ]
ma_stuff=[ "${ext_lua}", "build/${version}/miniaudio", "copy" ]
vk_spv_stuff=[ "${ext_spv}", "build/${version}/spirv-reflect", "copy" ]
vk_win_stuff=[ "${ext_vk}", "build/${version}/vulkan", "copy" ] # Only windows-gnu needs vk stuff

[linux-sync]
kw_stuff=[ "${dir_kw}", "${ext_kw}", "copy" ]
kg_stuff=[ "${dir_kg}", "${ext_kg}", "copy" ]
kg_files=[ "${kg_files}", "${ext_kg}/files", "copy" ]
kp_stuff=[ "${dir_kp}", "${ext_kp}", "copy" ]
ks_stuff=[ "${dir_ks}", "${ext_ks}", "copy" ]
kl_stuff=[ "${dir_kl}", "${ext_kl}", "copy" ]
ka_stuff=[ "${dir_ka}", "${ext_ka}", "copy" ]
kh_license=[ "${dir_kh}/LICENSE.md", "${ext_kh}/LICENSE.md", "copy" ]
kh_readme=[ "${dir_kh}/README.md", "${ext_kh}/README.md", "copy" ]
kh_include=[ "${dir_kh}/include", "${ext_kh}/include", "copy" ]
cg_stuff=[ "${dir_cg}", "${ext_cg}", "copy" ]
hb_stuff=[ "${dir_hb}", "${ext_hb}", "copy" ]
lo_stuff=[ "${dir_lo}", "${ext_lo}", "copy" ]
lua_stuff=[ "${dir_lua}", "${ext_lua}", "copy" ]
ma_stuff=[ "${dir_ma}", "${ext_ma}", "copy" ]
vk_win_stuff=[ "${dir_vk_win}", "${ext_vk}", "copy" ]
vk_spv_stuff=[ "${dir_vk_spv}", "${ext_spv}", "copy" ]
kw_junk_kh=[ "${ext_kw}/kalaheaders", "", "delete" ]
kw_junk_vk_win=[ "${ext_kw}/vulkan", "", "delete" ]
kw_junk_vk_spv=[ "${ext_kw}/spirv-reflect", "", "delete" ]
kg_junk_kh=[ "${ext_kg}/kalaheaders", "", "delete" ]
kg_junk_cg=[ "${ext_kg}/cgltf", "", "delete" ]
kg_junk_hb=[ "${ext_kg}/harfbuzz", "", "delete" ]
kg_junk_lo=[ "${ext_kg}/lodepng", "", "delete" ]
kg_junk_vk_win=[ "${ext_kg}/vulkan", "", "delete" ]
kg_junk_vk_spv=[ "${ext_kg}/spirv-reflect", "", "delete" ]
kp_junk_kh=[ "${ext_kp}/kalaheaders", "", "delete" ]
ks_junk_kh=[ "${ext_ks}/kalaheaders", "", "delete" ]
kl_junk_kh=[ "${ext_kl}/kalaheaders", "", "delete" ]
kl_junk_lua=[ "${ext_kl}/lua", "", "delete" ]
ka_junk_kh=[ "${ext_ka}/kalaheaders", "", "delete" ]
ka_junk_ma=[ "${ext_ka}/miniaudio", "", "delete" ]

[linux-post-build-sync]
ee_bin_rel=[ "build/temp/release-linux/libelypsoengine.a", "build/${version}/libelypsoengine.a", "copy" ]
ee_bin_deb=[ "build/temp/debug-linux/libelypsoengined.a", "build/${version}/libelypsoengined.a", "copy" ]
ee_include=[ "include", "build/${version}/include", "copy" ]
ee_license=[ "../LICENSE.md", "build/${version}/LICENSE.md", "copy" ]
ee_readme=[ "../README.md", "build/${version}/README.md", "copy" ]
ee_changes=[ "CHANGES.md", "build/${version}/CHANGES.md", "copy" ]
kw_stuff=[ "${ext_kw}", "build/${version}/kalawindow", "copy" ]
kg_stuff=[ "${ext_kg}", "build/${version}/kalagraphics", "copy" ]
kp_stuff=[ "${ext_kp}", "build/${version}/kalaphysics", "copy" ]
ks_stuff=[ "${ext_ks}", "build/${version}/kalaserver", "copy" ]
kl_stuff=[ "${ext_kl}", "build/${version}/kalalua", "copy" ]
ka_stuff=[ "${ext_ka}", "build/${version}/kalaaudio", "copy" ]
kh_stuff=[ "${ext_kh}", "build/${version}/kalaheaders", "copy" ]
cg_stuff=[ "${ext_cg}", "build/${version}/cgltf", "copy" ]
hb_stuff=[ "${ext_hb}", "build/${version}/harfbuzz", "copy" ]
lo_stuff=[ "${ext_lo}", "build/${version}/lodepng", "copy" ]
lua_stuff=[ "${ext_lua}", "build/${version}/lua", "copy" ]
ma_stuff=[ "${ext_lua}", "build/${version}/miniaudio", "copy" ]
vk_spv_stuff=[ "${ext_spv}", "build/${version}/spirv-reflect", "copy" ]
